name: Build & Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - run: yarn
      - run: yarn build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-storybook
          clean: true
